language: python

matrix:
  include:
    - os: linux
      sudo: false
      python: "2.7"
    - os: linux
      sudo: false
      python: "3.2"
    - os: linux
      sudo: false
      python: "3.3"
    - os: linux
      sudo: false
      python: "3.4"
    - os: linux
      sudo: false
      python: "3.5"
    - os: linux
      sudo: false
      python: "pypy"
    - os: linux
      sudo: required
      dist: trusty
      python: "2.7"
    - os: osx
      osx_image: xcode6.4
      language: generic

addons:
  apt:
    packages:
      - cmake
      - scons
      - qt4-qmake

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update;            fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python;    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake;     fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install scons;     fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt;        fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install coreutils; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl http://llvm.org/releases/3.7.0/clang+llvm-3.7.0-x86_64-apple-darwin.tar.xz -o clang+llvm-3.7.0-x86_64-apple-darwin.tar.xz; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tar xf clang+llvm-3.7.0-x86_64-apple-darwin.tar.xz -C ~/; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=~/clang+llvm-3.7.0-x86_64-apple-darwin/bin/:$PATH; fi

install:
  - pip install pep8

script:
  - pep8 bear/main.py.in
  - cmake . -DCPACK_GENERATOR="TGZ;DEB"
  - make all
  - make check
  - mkdir target_dir
  - DESTDIR=target_dir make install
  - make package
